const language = {
  en: {
    search: "Search",
    gptSearchPlaceHolder: "What would you like to watch today?",
    nowPlayingMovies: "Now Playing Movies",
    popularMovies: "Popular",
    topRatedMovies: "Top-Rated Movies",
    upcomingMovies: "Upcoming",
    play: "Play",
    signOut: "Sign Out",
    gpt: "GPT",
    home: "Home",
    moreInfo: "More Info",
    searchResultsFor: "search results for",
    allTrending: "Trending Now",
    trendingMovies: "Trending Movies",
    trendingTV: "Trending TV Shows",
    airingToday: "Airing Today",
    topRatedTV: "Top-Rated TV Shows",
  },
  hindi: {
    search: "खोज",
    gptSearchPlaceHolder: "आज आप क्या देखना चाहेंगे?",
    nowPlayingMovies: "फिल्में इस समय",
    popularMovies: "लोकप्रिय",
    topRatedMovies: "टॉप रेटेड फिल्में",
    upcomingMovies: "आगामी",
    play: "शुरू",
    signOut: "साइन आउट",
    gpt: "जीपीटी",
    home: "होम",
    moreInfo: "अधिक जानकारी",
    searchResultsFor: "खोज परिणाम",
    allTrending: "ट्रेंडिंग नाव",
    trendingMovies: "ट्रेंडिंग फिल्में",
    trendingTV: "ट्रेंडिंग टीवी शो",
    airingToday: "आज प्रसारित हो रहा है",
    topRatedTV: "टॉप रेटेड टीवी शो",
  },
  french: {
    search: "recherche",
    gptSearchPlaceHolder: "Qu’aimeriez-vous regarder aujourd’hui?",
    nowPlayingMovies: "Lecture en cours",
    popularMovies: "populaire",
    topRatedMovies: "Les mieux notés film",
    upcomingMovies: "A venir",
    play: "jouer",
    signOut: "se déconnecter",
    gpt: "GPT",
    home: "home",
    moreInfo: "plus d'informations",
    searchResultsFor: "Résultats de recherche pour",
    allTrending: "tendance maintenant",
    trendingMovies: "films tendances",
    trendingTV: "ÉMISSIONS TV tendances",
    airingToday: "diffusé aujourd'hui",
    topRatedTV: "Émissions de télévision les mieux notées",
  },
  spanish: {
    search: "buscar",
    gptSearchPlaceHolder: "¿Qué te gustaría ver hoy?",
    nowPlayingMovies: "Jugando ahora",
    popularMovies: "popular",
    topRatedMovies: "Los más valorados película",
    upcomingMovies: "Próximo",
    play: "jugar",
    signOut: "desconectar",
    gpt: "GPT",
    home: "home",
    moreInfo: "más información",
    searchResultsFor: "resultados de búsqueda para",
    allTrending: "tendencias ahora",
    trendingMovies: "películas de tendencia",
    trendingTV: "Programas de televisión de tendencia",
    airingToday: "transmitiendo hoy",
    topRatedTV: "Programas de televisión mejor valorados",
  },
};

export default language;
