const language = {
  en: {
    search: "Search",
    gptSearchPlaceHolder: "What would you like to watch today?",
    nowPlaying: "Now Playing",
    popular: "Popular",
    topRated: "Top-Rated",
    upcoming: "Upcoming",
    play: "Play",
    signOut: "Sign Out",
    gpt: "GPT",
    home: "Home",
    moreInfo: "More Info",
    searchResultsFor: "search results for",
  },
  hindi: {
    search: "खोज",
    gptSearchPlaceHolder: "आज आप क्या देखना चाहेंगे?",
    nowPlaying: "इस समय",
    popular: "लोकप्रिय",
    topRated: "टॉप रेटेड",
    upcoming: "आगामी",
    play: "शुरू",
    signOut: "साइन आउट",
    gpt: "जीपीटी",
    home: "होम",
    moreInfo: "अधिक जानकारी",
    searchResultsFor: "खोज परिणाम",
  },
  french: {
    search: "recherche",
    gptSearchPlaceHolder: "Qu’aimeriez-vous regarder aujourd’hui?",
    nowPlaying: "Lecture en cours",
    popular: "populaire",
    topRated: "Les mieux notés",
    upcoming: "A venir",
    play: "jouer",
    signOut: "se déconnecter",
    gpt: "GPT",
    home: "home",
    moreInfo: "plus d'informations",
    searchResultsFor: "Résultats de recherche pour",
  },
  spanish: {
    search: "buscar",
    gptSearchPlaceHolder: "¿Qué te gustaría ver hoy?",
    nowPlaying: "Jugando ahora",
    popular: "popular",
    topRated: "Los más valorados",
    upcoming: "Próximo",
    play: "jugar",
    signOut: "desconectar",
    gpt: "GPT",
    home: "home",
    moreInfo: "más información",
    searchResultsFor: "resultados de búsqueda para",
  },
};

export default language;
